series:
  - id: F032.PIB.FLU.R.CLP.EP18.Z.Z.0.T
    group: dashboard
  - id: F074.IPC.IND.Z.EP09.C.M
    group: dashboard
  - id: F049.DES.TAS.INE9.10.M
    group: dashboard
  - id: F032.IMC.IND.Z.Z.EP18.Z.Z.0.M
    group: dashboard
  - id: F022.TPM.TIN.D001.NO.Z.D
    group: dashboard
  - id: F073.TCO.PRE.Z.D
    group: dashboard
  - id: F073.UFF.PRE.Z.D
    group: dashboard
  - id: F073.UTR.PRE.Z.M
    group: dashboard
